// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"worker/dal"
	"worker/operator"
	"worker/service"
)

// Injectors from wire.go:

func InitContainer() (*Container, error) {
	mongoClient, err := dal.NewMongoClient()
	if err != nil {
		return nil, err
	}
	mongoOperator, err := operator.NewMongoOperator(mongoClient)
	if err != nil {
		return nil, err
	}
	storageOperator := operator.NewStorageOperator()
	fileService := service.NewFileService(mongoOperator, storageOperator)
	bucketService := service.NewBucketService(mongoOperator, fileService)
	userService := service.NewUserService(mongoOperator)
	heartbeatService := service.NewHeartbeatService(mongoOperator, storageOperator)
	prometheusService := service.NewPrometheusService(mongoOperator)
	container := NewContainer(mongoClient, mongoOperator, storageOperator, bucketService, fileService, userService, heartbeatService, prometheusService)
	return container, nil
}
